Repository Resilient-Labs/nourish, pull requests merged in 2024-01, with the labels that each got.

#131 changed routes and files from fridgeLanding to locations, added volun…
  client/src/App.css
  client/src/App.js
  client/src/pages/FridgeLanding.js
  client/src/pages/FridgeProfile.js
Labels: frontend

#133 BE team member controller added
  server/controllers/ourTeam.js
  server/controllers/posts.js
Labels: backend

#135 fe- wip add user profile with contact and password change
  client/src/components/Navbar.js
  client/src/pages/UserProfile.js
Labels: frontend

#137 Be fixing login issue and testing community board
  client/src/components/AllPosts.js
  client/src/components/MessageBoardInteractive.js
  client/src/pages/Login.js
  client/src/pages/SignUp.js
  server/controllers/posts.js
  server/models/Post.js
  server/server.js
Labels: bug, backend, frontend

#138 Be ro quick updates ensure auth
  server/routes/posts.js
Labels: backend

#136 Add routes for team member profiles and changed controller file name
  server/controllers/team.js
  server/routes/team.js
  server/server.js
Labels: backend

#145 fe-add-social-btns-and-comment-section
  client/src/components/AllPosts.js
  client/src/components/CommentBox.js
  client/src/components/SocialButtons.js
Labels: frontend

#147 shows errors to user if error occurs during signup or login
  client/src/pages/Login.js
  client/src/pages/SignUp.js
Labels: backend, frontend

#146 gitignore fix
  .gitignore
  client/.gitignore
  client/package-lock.json
  client/src/components/Navbar.js
Labels: enhancement

#149 Fe be setup delete btn
  client/src/components/AllPosts.js
  client/src/components/MessageBoardInteractive.js
  client/src/components/SocialButtons.js
  server/controllers/posts.js
  server/routes/main.js
Labels: backend, frontend

#151 small fix
  server/controllers/team.js
Labels: backend

#152 auto refresh for community posts
  client/src/components/AllPosts.js
  client/src/components/MessageBoardInteractive.js
  client/src/pages/Community.js
Labels: frontend

#154 commenting and display of comments
  client/src/components/AllPosts.js
  client/src/components/CommentBox.js
  client/src/components/CommentButtons.js
  client/src/pages/Community.js
  server/controllers/posts.js
  server/models/Post.js
Labels: backend, frontend

#160 Navbar conditional for displaying Profile/Log Out vs. Log In/Sign Up
  client/src/App.js
  client/src/components/Navbar.js
  client/src/pages/Community.js
  client/src/pages/FridgeLocations.js
  client/src/pages/FridgeProfile.js
  client/src/pages/Home.js
  client/src/pages/Login.js
  client/src/pages/SignUp.js
  client/src/pages/UserProfile.js
Labels: frontend

#158 post without images and delete posts without images
  server/controllers/posts.js
Labels: backend

#161 just some psuedo code for backend
  server/controllers/auth.js
  server/controllers/fridge.js
  server/controllers/profile.js
  server/controllers/team.js
  server/routes/fridge.js
  server/routes/main.js
  server/routes/profile.js
  server/server.js
Labels: backend

#163 Fe interactive map about me
  client/src/components/Fridge.js
  client/src/components/FridgeList.js
  client/src/components/FridgeMap.js
  client/src/components/Searchbar.js
Labels: frontend

#169 FE - community wall, BE - Reload of comments without full page reload
  client/src/App.js
  client/src/components/AllPosts.js
  client/src/components/CommentBox.js
  client/src/components/CommentButtons.js
  client/src/components/ProtectedRoute.js
  client/src/pages/Login.js
  client/src/pages/SignUp.js
  server/controllers/posts.js
  server/routes/posts.js
Labels: backend, frontend

#171 Make logout button log user out successfully
  client/src/App.js
  client/src/components/Navbar.js
  server/controllers/auth.js
  server/server.js
Labels: backend, frontend
